/* Auto-generated by tests/fixer_sanity/gen_fixer_registry.py. DO NOT EDIT. */
#include <stddef.h>
#include "fixer_registry.h"
#include "adapter.h"

/* Include implementation so even static fixers are visible. */
#include "../../llm/dtls/dtls_fixers.c"

static int __wrap_fix_monotonic_message_seq(proto_packet_t *pkts, int num) { fix_monotonic_message_seq(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_0_clienthello_first(proto_packet_t *pkts, int num) { fix_c2s_shot_0_clienthello_first(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_2_clienthello_cipher_suites_len(proto_packet_t *pkts, int num) { fix_c2s_shot_2_clienthello_cipher_suites_len(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_3_clienthello_compression_methods(proto_packet_t *pkts, int num) { fix_c2s_shot_3_clienthello_compression_methods(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_4_clienthello_extensions_len(proto_packet_t *pkts, int num) { fix_c2s_shot_4_clienthello_extensions_len(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_6_clienthello_session_id_len(proto_packet_t *pkts, int num) { fix_c2s_shot_6_clienthello_session_id_len(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_11_clienthello_cookie_len(proto_packet_t *pkts, int num) { fix_c2s_shot_11_clienthello_cookie_len(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_23_ccs_before_finished(proto_packet_t *pkts, int num) { fix_c2s_shot_23_ccs_before_finished(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_24_ccs_value(proto_packet_t *pkts, int num) { fix_c2s_shot_24_ccs_value(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_25_finished_after_ccs(proto_packet_t *pkts, int num) { fix_c2s_shot_25_finished_after_ccs(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_28_29_handshake_order(proto_packet_t *pkts, int num) { fix_c2s_shot_28_29_handshake_order(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_30_34_no_appdata_before_done(proto_packet_t *pkts, int num) { fix_c2s_shot_30_34_no_appdata_before_done(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_31_monotonic_message_seq(proto_packet_t *pkts, int num) { fix_c2s_shot_31_monotonic_message_seq(pkts, num); return 0; }
static int __wrap_fix_c2s_shot_32_fragment_length_ok(proto_packet_t *pkts, int num) { fix_c2s_shot_32_fragment_length_ok(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_0_serverhello_first(proto_packet_t *pkts, int num) { fix_s2c_shot_0_serverhello_first(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_1_server_version_le_client(proto_packet_t *pkts, int num) { fix_s2c_shot_1_server_version_le_client(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_3_serverhello_session_id_len(proto_packet_t *pkts, int num) { fix_s2c_shot_3_serverhello_session_id_len(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_4_serverhello_cipher_suite_from_client(proto_packet_t *pkts, int num) { fix_s2c_shot_4_serverhello_cipher_suite_from_client(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_5_serverhello_compression_from_client(proto_packet_t *pkts, int num) { fix_s2c_shot_5_serverhello_compression_from_client(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_6_serverhello_extensions_len(proto_packet_t *pkts, int num) { fix_s2c_shot_6_serverhello_extensions_len(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_10_hvr_cookie_len(proto_packet_t *pkts, int num) { fix_s2c_shot_10_hvr_cookie_len(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_11_hvr_version_le_client(proto_packet_t *pkts, int num) { fix_s2c_shot_11_hvr_version_le_client(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_22_certreq_before_shd(proto_packet_t *pkts, int num) { fix_s2c_shot_22_certreq_before_shd(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_23_certreq_cert_types_nonempty(proto_packet_t *pkts, int num) { fix_s2c_shot_23_certreq_cert_types_nonempty(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_24_certreq_sig_algs_even(proto_packet_t *pkts, int num) { fix_s2c_shot_24_certreq_sig_algs_even(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_25_certreq_ca_dn_len(proto_packet_t *pkts, int num) { fix_s2c_shot_25_certreq_ca_dn_len(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_28_29_server_ccs_before_finished(proto_packet_t *pkts, int num) { fix_s2c_shot_28_29_server_ccs_before_finished(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_30_31_server_finished_after_ccs(proto_packet_t *pkts, int num) { fix_s2c_shot_30_31_server_finished_after_ccs(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_33_34_server_order_and_no_appdata(proto_packet_t *pkts, int num) { fix_s2c_shot_33_34_server_order_and_no_appdata(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_35_36_dtls_seq_and_frag(proto_packet_t *pkts, int num) { fix_s2c_shot_35_36_dtls_seq_and_frag(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_38_alert_two_bytes(proto_packet_t *pkts, int num) { fix_s2c_shot_38_alert_two_bytes(pkts, num); return 0; }
static int __wrap_fix_s2c_shot_40_no_appdata_before_done(proto_packet_t *pkts, int num) { fix_s2c_shot_40_no_appdata_before_done(pkts, num); return 0; }
static int __wrap_fix_common_lengths_and_kinds(proto_packet_t *pkts, int num) { fix_common_lengths_and_kinds(pkts, num); return 0; }

const fixer_desc_t g_fixers[] = {
  {"fix_monotonic_message_seq", (fixer_fn_t)__wrap_fix_monotonic_message_seq},
  {"fix_c2s_shot_0_clienthello_first", (fixer_fn_t)__wrap_fix_c2s_shot_0_clienthello_first},
  {"fix_c2s_shot_2_clienthello_cipher_suites_len", (fixer_fn_t)__wrap_fix_c2s_shot_2_clienthello_cipher_suites_len},
  {"fix_c2s_shot_3_clienthello_compression_methods", (fixer_fn_t)__wrap_fix_c2s_shot_3_clienthello_compression_methods},
  {"fix_c2s_shot_4_clienthello_extensions_len", (fixer_fn_t)__wrap_fix_c2s_shot_4_clienthello_extensions_len},
  {"fix_c2s_shot_6_clienthello_session_id_len", (fixer_fn_t)__wrap_fix_c2s_shot_6_clienthello_session_id_len},
  {"fix_c2s_shot_11_clienthello_cookie_len", (fixer_fn_t)__wrap_fix_c2s_shot_11_clienthello_cookie_len},
  {"fix_c2s_shot_23_ccs_before_finished", (fixer_fn_t)__wrap_fix_c2s_shot_23_ccs_before_finished},
  {"fix_c2s_shot_24_ccs_value", (fixer_fn_t)__wrap_fix_c2s_shot_24_ccs_value},
  {"fix_c2s_shot_25_finished_after_ccs", (fixer_fn_t)__wrap_fix_c2s_shot_25_finished_after_ccs},
  {"fix_c2s_shot_28_29_handshake_order", (fixer_fn_t)__wrap_fix_c2s_shot_28_29_handshake_order},
  {"fix_c2s_shot_30_34_no_appdata_before_done", (fixer_fn_t)__wrap_fix_c2s_shot_30_34_no_appdata_before_done},
  {"fix_c2s_shot_31_monotonic_message_seq", (fixer_fn_t)__wrap_fix_c2s_shot_31_monotonic_message_seq},
  {"fix_c2s_shot_32_fragment_length_ok", (fixer_fn_t)__wrap_fix_c2s_shot_32_fragment_length_ok},
  {"fix_s2c_shot_0_serverhello_first", (fixer_fn_t)__wrap_fix_s2c_shot_0_serverhello_first},
  {"fix_s2c_shot_1_server_version_le_client", (fixer_fn_t)__wrap_fix_s2c_shot_1_server_version_le_client},
  {"fix_s2c_shot_3_serverhello_session_id_len", (fixer_fn_t)__wrap_fix_s2c_shot_3_serverhello_session_id_len},
  {"fix_s2c_shot_4_serverhello_cipher_suite_from_client", (fixer_fn_t)__wrap_fix_s2c_shot_4_serverhello_cipher_suite_from_client},
  {"fix_s2c_shot_5_serverhello_compression_from_client", (fixer_fn_t)__wrap_fix_s2c_shot_5_serverhello_compression_from_client},
  {"fix_s2c_shot_6_serverhello_extensions_len", (fixer_fn_t)__wrap_fix_s2c_shot_6_serverhello_extensions_len},
  {"fix_s2c_shot_10_hvr_cookie_len", (fixer_fn_t)__wrap_fix_s2c_shot_10_hvr_cookie_len},
  {"fix_s2c_shot_11_hvr_version_le_client", (fixer_fn_t)__wrap_fix_s2c_shot_11_hvr_version_le_client},
  {"fix_s2c_shot_22_certreq_before_shd", (fixer_fn_t)__wrap_fix_s2c_shot_22_certreq_before_shd},
  {"fix_s2c_shot_23_certreq_cert_types_nonempty", (fixer_fn_t)__wrap_fix_s2c_shot_23_certreq_cert_types_nonempty},
  {"fix_s2c_shot_24_certreq_sig_algs_even", (fixer_fn_t)__wrap_fix_s2c_shot_24_certreq_sig_algs_even},
  {"fix_s2c_shot_25_certreq_ca_dn_len", (fixer_fn_t)__wrap_fix_s2c_shot_25_certreq_ca_dn_len},
  {"fix_s2c_shot_28_29_server_ccs_before_finished", (fixer_fn_t)__wrap_fix_s2c_shot_28_29_server_ccs_before_finished},
  {"fix_s2c_shot_30_31_server_finished_after_ccs", (fixer_fn_t)__wrap_fix_s2c_shot_30_31_server_finished_after_ccs},
  {"fix_s2c_shot_33_34_server_order_and_no_appdata", (fixer_fn_t)__wrap_fix_s2c_shot_33_34_server_order_and_no_appdata},
  {"fix_s2c_shot_35_36_dtls_seq_and_frag", (fixer_fn_t)__wrap_fix_s2c_shot_35_36_dtls_seq_and_frag},
  {"fix_s2c_shot_38_alert_two_bytes", (fixer_fn_t)__wrap_fix_s2c_shot_38_alert_two_bytes},
  {"fix_s2c_shot_40_no_appdata_before_done", (fixer_fn_t)__wrap_fix_s2c_shot_40_no_appdata_before_done},
  {"fix_common_lengths_and_kinds", (fixer_fn_t)__wrap_fix_common_lengths_and_kinds},
};

const size_t g_fixers_count = sizeof(g_fixers) / sizeof(g_fixers[0]);
