/* Auto-generated by tests/mutator_sanity/gen_mutator_registry.py. DO NOT EDIT. */
#include <stddef.h>
#include "mutator_registry.h"
#include "adapter.h"

/* Include mutator implementation so even static mutators are visible here. */
#include "../../../llm/smtp/smtp_mutators.c"

const mutator_desc_t g_mutators[] = {
  {"mutate_helo_domain", (mutator_fn_t)mutate_helo_domain},
  {"mutate_ehlo_domain", (mutator_fn_t)mutate_ehlo_domain},
  {"mutate_mail_reverse_path", (mutator_fn_t)mutate_mail_reverse_path},
  {"add_mail_optional_args", (mutator_fn_t)add_mail_optional_args},
  {"delete_mail_optional_args", (mutator_fn_t)delete_mail_optional_args},
  {"mutate_mail_optional_args", (mutator_fn_t)mutate_mail_optional_args},
  {"mutate_rcpt_forward_path", (mutator_fn_t)mutate_rcpt_forward_path},
  {"add_rcpt_optional_args", (mutator_fn_t)add_rcpt_optional_args},
  {"delete_rcpt_optional_args", (mutator_fn_t)delete_rcpt_optional_args},
  {"mutate_rcpt_optional_args", (mutator_fn_t)mutate_rcpt_optional_args},
  {"mutate_vrfy_string", (mutator_fn_t)mutate_vrfy_string},
  {"mutate_expn_mailing_list", (mutator_fn_t)mutate_expn_mailing_list},
  {"add_smtp_help_argument", (mutator_fn_t)add_smtp_help_argument},
  {"delete_smtp_help_argument", (mutator_fn_t)delete_smtp_help_argument},
  {"mutate_smtp_help_argument", (mutator_fn_t)mutate_smtp_help_argument},
  {"add_auth_initial_response", (mutator_fn_t)add_auth_initial_response},
  {"delete_auth_initial_response", (mutator_fn_t)delete_auth_initial_response},
  {"mutate_auth_initial_response", (mutator_fn_t)mutate_auth_initial_response},
};

const size_t g_mutators_count = sizeof(g_mutators) / sizeof(g_mutators[0]);
